# These are supported funding model platforms

github: [ajmeese7]
open_collective: ajmeese7
ko_fi: aaronmeese
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: ajmeese7 # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
