name: Publish Package on Version Change

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: pnpm install

    - name: Login to Wrangler
      shell: bash
      run: |
        echo "$CLOUDFLARE_API_KEY" | npx wrangler config
      env:
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}

    - name: Publish to npmjs Package Registry
      run: |
        pnpm publish --publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
